### ISSUE TITLE
error with notion database ID?

### ISSUE THREAD

**Issue by bmsacchi** [apoorvkh/paperpile-to-notion#1]
Hi!
I'm having an issue getting the notion database to connect - the bibtext file updates just fine. I've tried copying the database identifier, the database identifier + whatever comes after ?v=, and the entire URL into DATABASE_IDENTIFIER, none of which work. I wasn't able to share the database with the paperpile to notion integration as instructed, but was able to using the "add connections" in the paperpile  menu. This is the error message I keep getting:

```
Run python -m paperpile_to_notion
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.[1](https://github.com/bmsacchi/paperpile-to-notion/actions/runs/5034748104/jobs/9029722950#step:5:1)6/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.[16](https://github.com/bmsacchi/paperpile-to-notion/actions/runs/5034748104/jobs/9029722950#step:5:17)/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line 116, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line 46, in main
Loading config from data_config.csv ...
Parsing references.bib ...
Querying Notion DB ...
    notion_pages = notion.query_db(db_id=DATABASE_IDENTIFIER, headers=NOTION_HEADERS)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/utils/notion.py", line 26, in query_db
    pages += response["results"]
KeyError: 'results'
Error: Process completed with exit code 1.
```
Hoping you can help me figure out if I've done anything wrong here! Thanks so much!

**Comment by apoorvkh** [comment]
Hey, thanks for trying this out. Maybe you understood this, but just to clarify, your database identifier should not be the whole link and should not include the contents after `?v=`: so the link might be structured like this `https://www.notion.so/USERNAME/DATABASE_IDENTIFIER?v=VIEW_ID`.

Just to be clear, in `Notion > Settings & Members > Connections`, you have the Paperpile to Notion connection (and have copied the internal integration token as NOTION_TOKEN in your Github Secrets):

<img width="891" alt="image" src="https://github.com/apoorvkh/paperpile-to-notion/assets/7005565/95a436d2-6cdd-4fd4-9744-8da2d5a2f985">

And, from the menu button of your database, you've also added this connection:

<img width="458" alt="image" src="https://github.com/apoorvkh/paperpile-to-notion/assets/7005565/68d4e277-856a-440f-bfd4-71961b85f153">

Does that all look correct? If so, are you able to test this locally? Can you modify this line
`File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/utils/notion.py", line 26, in query_db` and `print(response, flush=True)` before this, so we can see the specific error?

**Comment by bmsacchi** [comment]
Hi Apoorv, thanks for the suggestions. Yes, I've double checked that the database ID and notion connection is set up correctly. Here's the output of printing the response:
```
Traceback (most recent call last):
Loading config from data_config.csv ...
Parsing references.bib ...
Querying Notion DB ...
{'object': 'list', 'results': [{'object': 'page', 'id': '03e5c878-44e5-42b4-a862-d060b3171cab', 'created_time': '2023-05-20T23:51:00.000Z', 'last_edited_time': '2023-05-20T23:51:00.000Z', 'created_by': {'object': 'user', 'id': '6ccda1d4-d122-463d-a4f8-9b51a4f862d3'}, 'last_edited_by': {'object': 'user', 'id': '6ccda1d4-d122-463d-a4f8-9b51a4f862d3'}, 'cover': None, 'icon': None, 'parent': {'type': 'database_id', 'database_id': '19bb2a31-51b5-4b10-9602-d81f[15](https://github.com/bmsacchi/paperpile-to-notion/actions/runs/5039952567/jobs/9038420383#step:5:16)1307df'}, 'archived': False, 'properties': {'Title': {'id': 'L%7B%3ET', 'type': 'rich_text', 'rich_text': []}, 'Authors': {'id': 'YhBP', 'type': 'rich_text', 'rich_text': []}, 'Year': {'id': '%60wJr', 'type': 'rich_text', 'rich_text': []}, 'Reference ID': {'id': 'title', 'type': 'title', 'title': []}}, 'url': 'https://www.notion.so/03e5c87844e542b4a862d060b3171cab'}, {'object': 'page', 'id': '43fe9e5e-3ac6-4528-bad0-f94488e10d66', 'created_time': '2023-05-20T23:51:00.000Z', 'last_edited_time': '2023-05-20T23:51:00.000Z', 'created_by': {'object': 'user', 'id': '6ccda1d4-d122-463d-a4f8-9b51a4f862d3'}, 'last_edited_by': {'object': 'user', 'id': '6ccda1d4-d122-463d-a4f8-9b51a4f862d3'}, 'cover': None, 'icon': None, 'parent': {'type': 'database_id', 'database_id': '19bb2a31-51b5-4b10-9602-d81f151307df'}, 'archived': False, 'properties': {'Title': {'id': 'L%7B%3ET', 'type': 'rich_text', 'rich_text': []}, 'Authors': {'id': 'YhBP', 'type': 'rich_text', 'rich_text': []}, 'Year': {'id': '%60wJr', 'type': 'rich_text', 'rich_text': []}, 'Reference ID': {'id': 'title', 'type': 'title', 'title': []}}, 'url': 'https://www.notion.so/43fe9e5e3ac64528bad0f94488e10d66'}, {'object': 'page', 'id': 'e3eae437-3ae6-447e-aaf4-dd59b8c9a17d', 'created_time': '2023-05-20T23:51:00.000Z', 'last_edited_time': '2023-05-20T23:51:00.000Z', 'created_by': {'object': 'user', 'id': '6ccda1d4-d122-463d-a4f8-9b51a4f862d3'}, 'last_edited_by': {'object': 'user', 'id': '6ccda1d4-d122-463d-a4f8-9b51a4f862d3'}, 'cover': None, 'icon': None, 'parent': {'type': 'database_id', 'database_id': '19bb2a31-51b5-4b10-9602-d81f151307df'}, 'archived': False, 'properties': {'Title': {'id': 'L%7B%3ET', 'type': 'rich_text', 'rich_text': []}, 'Authors': {'id': 'YhBP', 'type': 'rich_text', 'rich_text': []}, 'Year': {'id': '%60wJr', 'type': 'rich_text', 'rich_text': []}, 'Reference ID': {'id': 'title', 'type': 'title', 'title': []}}, 'url': 'https://www.notion.so/e3eae4373ae6447eaaf4dd59b8c9a17d'}], 'next_cursor': None, 'has_more': False, 'type': 'page', 'page': {}}
  File "/opt/hostedtoolcache/Python/3.9.[16](https://github.com/bmsacchi/paperpile-to-notion/actions/runs/5039952567/jobs/9038420383#step:5:17)/x64/lib/python3.9/runpy.py", line [19](https://github.com/bmsacchi/paperpile-to-notion/actions/runs/5039952567/jobs/9038420383#step:5:20)7, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line 116, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line 48, in main
    notion_entries = [
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line 49, in <listcomp>
    {
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line 50, in <dictcomp>
    c["notion_property"]: notion.get_property(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/utils/notion.py", line 71, in get_property
    content = p["title"][0]["text"]["content"]
IndexError: list index out of range
Error: Process completed with exit code 1.
```
The notion links in there take me to empty pages within the database I created. Not sure how to decifer what went wrong here. Thanks!

**Comment by apoorvkh** [comment]
Looks like the error in your most recent message is different from your first error. Maybe there was an issue with the connection initially, but now we can definitely see that the query is successful.

I think the problem is that your database has two empty rows. Is that right? Can you delete these and try again?

I'm specifically noticing that the response that was generated has two elements in response["results"] and both of these have empty fields:

```
            "properties": {
                "Title": {"id": "L%7B%3ET", "type": "rich_text", "rich_text": []},
                "Authors": {"id": "YhBP", "type": "rich_text", "rich_text": []},
                "Year": {"id": "%60wJr", "type": "rich_text", "rich_text": []},
                "Reference ID": {"id": "title", "type": "title", "title": []},
            },
```

**Comment by bmsacchi** [comment]
Deleting the empty rows worked! Thanks!

**Comment by apoorvkh** [comment]
Great! I'll also try to write my own instructions to use this library sometime later, maybe that will help.
