### ISSUE TITLE
paperpile_to_notion script failing with Index Error

### ISSUE THREAD

**Issue by wildbill12** [apoorvkh/paperpile-to-notion#3]
This is the error I'm consistently getting now

Is it potentially something with how the Notion database is set up?  I believe I have it done right

Run python -m paperpile_to_notion
##[debug]/usr/bin/bash -e /home/runner/work/_temp/67c171cc-e7fa-4f0e-831e-e71a036818c2.sh
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line 116, in <module>
    main()
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line [48](https://github.com/wildbill12/paperpile-to-notion/actions/runs/5218288639/jobs/9427167007#step:5:49), in main
    notion_entries = [
Loading config from data_config.csv ...
Parsing references.bib ...
Querying Notion DB ...
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line [49](https://github.com/wildbill12/paperpile-to-notion/actions/runs/5218288639/jobs/9427167007#step:5:50), in <listcomp>
    {
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/__main__.py", line [50](https://github.com/wildbill12/paperpile-to-notion/actions/runs/5218288639/jobs/9427167007#step:5:51), in <dictcomp>
    c["notion_property"]: notion.get_property(
  File "/opt/hostedtoolcache/Python/3.9.16/x64/lib/python3.9/site-packages/paperpile_to_notion/utils/notion.py", line 70, in get_property
    content = p["title"][0]["text"]["content"]
IndexError: list index out of range
Error: Process completed with exit code 1.

**Comment by apoorvkh** [comment]
Do you think there are entries in your Notion DB with no title?

I just pushed a change in 18e7d3fa12c93526427541d5dff70f5515017199: a quick fix to skip broken entries. Please update your fork of this repo and try again!

**Comment by apoorvkh** [comment]
Actually, I think your issue was also the same as #1.

**Comment by wildbill12** [comment]
The single blank row was the culprit!  

Definitely should put that in the instructions, a new table database just pops up with a few blank lines by default and I thought I had deleted them all but didn't.  Thanks!

**Comment by apoorvkh** [comment]
Glad it was resolved and good to know, thanks! Will add that to the instructions.
